# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86b0ac32271464c08c0874a951069a72fedfd493da32047fec2deddcc35cff4834bf99070a2eeab345558151e030fdfec5bb8a84a184734f99a4ae9da3c6db9d

test:
  secret_key_base: 9262f75ab805673f93728629217ab7e3fe70ac6d8725332d657c02a596c65a1d9b35b1f3d151ef52496c2fb8e1890f70e70fcc5f97b044a9465b2e5a4da7705f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
